# SPDX-FileCopyrightText: © 2024 Tiny Tapeout
# SPDX-License-Identifier: Apache-2.0

TOPLEVEL_LANG = verilog

VERILOG_SOURCES = ../src/project.v

TOPLEVEL = tt_um_4bit_comparator

MODULE = test

SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
